version: "3"
services: 
  scd-batch:
#    image: sergioadsf/scd-batch:1.4
    build: .
    container_name: scd-batch
    volumes:
    - ./target/scd-batch-0.0.1-SNAPSHOT.jar:/app.jar
    ports:
      - "8082:8082"
    command: ["java", "-jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005", "app.jar"]
    depends_on:
      - scd-elastic
    # links:
    #   - scd-elastic
    environment:
      - SCD_ELASTIC_URL=scd-elastic
      - SCD_ELASTIC_PORT=8083
    networks:
      - scd-network

  scd-elastic:
    image: sergioadsf/scd-elastic:1.3
    container_name: scd-elastic
#    ports:
#      - "8083:8083"
    depends_on:
      - elasticsearch
    environment:
      - SCD_ELASTICSEARCH_URL=elasticsearch
      - SCD_ELASTICSEARCH_PORT=9200
    # links:
    #   - elasticsearch
    networks:
       - scd-network

  elasticsearch:
    image: elasticsearch:6.6.1
    container_name: elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes: 
      - esdata1:/usr/share/elasticsearch/data
    networks:
       - scd-network
#    command: ["sysctl", "-w", "vm.max_map_count=262144"]
    environment:
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
      - "5601:5601"
    networks:
      - scd-network
    environment:
      # - SERVER_NAME=kibana.localhost
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
    depends_on:
      - elasticsearch
  #   links:
  #     - elasticsearch

networks:
  scd-network:
    driver: bridge

volumes: 
  esdata1:
    driver: local
